# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a9e7e994415e90defeac2dfcf86da8be187ea3c0ba73d18b83281ad6c0968759
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule RustyLlama.Context do
  @moduledoc """
  Handle to a running context actor. Clone + Send + Sync.

  The actor thread is stopped when the last clone is dropped.
  """

  alias RustyLlama.Native

  defstruct [:ref]

  @typedoc "Handle to a running context actor. Clone + Send + Sync."
  @type t :: %__MODULE__{ref: reference()}

  def new(model, params) do
    Native.context_new(model, params)
  end

  def sequence(obj) do
    Native.context_sequence(obj.ref)
  end

  def free_slots(obj) do
    Native.context_free_slots(obj.ref)
  end

  def n_ctx(obj) do
    Native.context_n_ctx(obj.ref)
  end

  def can_shift(obj) do
    Native.context_can_shift(obj.ref)
  end

  def perf(obj) do
    Native.context_perf(obj.ref)
  end
end
