# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a9e7e994415e90defeac2dfcf86da8be187ea3c0ba73d18b83281ad6c0968759
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule RustyLlama.DecodeError do
  @moduledoc false

  @type t :: :slot_not_found | :aborted | :invalid_input | :fatal_error

  @slot_not_found :slot_not_found
  @aborted :aborted
  @invalid_input :invalid_input
  @fatal_error :fatal_error

  @spec slot_not_found() :: t()
  def slot_not_found, do: @slot_not_found
  @spec aborted() :: t()
  def aborted, do: @aborted
  @spec invalid_input() :: t()
  def invalid_input, do: @invalid_input
  @spec fatal_error() :: t()
  def fatal_error, do: @fatal_error
end
