# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a9e7e994415e90defeac2dfcf86da8be187ea3c0ba73d18b83281ad6c0968759
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule RustyLlama.Model do
  @moduledoc """
  Thread-safe handle to a loaded model.

  Cloning is cheap (Arc bump). Use from any thread.
  """

  alias RustyLlama.Native

  defstruct [:ref]

  @typedoc "Thread-safe handle to a loaded model."
  @type t :: %__MODULE__{ref: reference()}

  def load_from_file(path, params) do
    Native.model_load_from_file(path, params)
  end

  def as_ptr(obj) do
    Native.model_as_ptr(obj.ref)
  end

  def chat_template(obj, name) do
    Native.model_chat_template(obj.ref, name)
  end

  def desc(obj) do
    Native.model_desc(obj.ref)
  end

  def has_decoder(obj) do
    Native.model_has_decoder(obj.ref)
  end

  def decoder_start_token(obj) do
    Native.model_decoder_start_token(obj.ref)
  end

  def has_encoder(obj) do
    Native.model_has_encoder(obj.ref)
  end

  def is_diffusion(obj) do
    Native.model_is_diffusion(obj.ref)
  end

  def is_hybrid(obj) do
    Native.model_is_hybrid(obj.ref)
  end

  def is_recurrent(obj) do
    Native.model_is_recurrent(obj.ref)
  end

  def token_to_piece(obj, token) do
    Native.model_token_to_piece(obj.ref, token)
  end

  def tokenize(obj, text, add_special, parse_special) do
    Native.model_tokenize(obj.ref, text, add_special, parse_special)
  end

  def get_add_bos(obj) do
    Native.model_get_add_bos(obj.ref)
  end

  def get_add_eos(obj) do
    Native.model_get_add_eos(obj.ref)
  end

  def get_add_sep(obj) do
    Native.model_get_add_sep(obj.ref)
  end

  def get_attr(obj, token) do
    Native.model_get_attr(obj.ref, token)
  end

  def get_score(obj, token) do
    Native.model_get_score(obj.ref, token)
  end

  def get_text(obj, token) do
    Native.model_get_text(obj.ref, token)
  end

  def is_control(obj, token) do
    Native.model_is_control(obj.ref, token)
  end

  def is_eog(obj, token) do
    Native.model_is_eog(obj.ref, token)
  end

  def n_tokens(obj) do
    Native.model_n_tokens(obj.ref)
  end

  def vocab_type(obj) do
    Native.model_vocab_type(obj.ref)
  end
end
