# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a9e7e994415e90defeac2dfcf86da8be187ea3c0ba73d18b83281ad6c0968759
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule RustyLlama.Native do
  @moduledoc false

  use RustlerPrecompiled,
    otp_app: :rusty_llama,
    crate: "rusty_llama_nif",
    base_url:
      "https://example.invalid/rusty-llama/releases/download/v#{Mix.Project.config()[:version]}",
    version: Mix.Project.config()[:version],
    targets: ~w(aarch64-apple-darwin aarch64-unknown-linux-gnu x86_64-unknown-linux-gnu x86_64-pc-windows-gnu),
    nif_versions: ["2.16", "2.17"],
    force_build: System.get_env("RUSTY_LLAMA_BUILD") in ["1", "true"] or Mix.env() in [:dev, :test]

  def model_load_from_file(_path, _params), do: :erlang.nif_error(:nif_not_loaded)
  def model_as_ptr(_obj), do: :erlang.nif_error(:nif_not_loaded)
  def model_chat_template(_obj, _name), do: :erlang.nif_error(:nif_not_loaded)
  def model_desc(_obj), do: :erlang.nif_error(:nif_not_loaded)
  def model_has_decoder(_obj), do: :erlang.nif_error(:nif_not_loaded)
  def model_decoder_start_token(_obj), do: :erlang.nif_error(:nif_not_loaded)
  def model_has_encoder(_obj), do: :erlang.nif_error(:nif_not_loaded)
  def model_is_diffusion(_obj), do: :erlang.nif_error(:nif_not_loaded)
  def model_is_hybrid(_obj), do: :erlang.nif_error(:nif_not_loaded)
  def model_is_recurrent(_obj), do: :erlang.nif_error(:nif_not_loaded)
  def model_token_to_piece(_obj, _token), do: :erlang.nif_error(:nif_not_loaded)
  def model_tokenize(_obj, _text, _add_special, _parse_special), do: :erlang.nif_error(:nif_not_loaded)
  def model_get_add_bos(_obj), do: :erlang.nif_error(:nif_not_loaded)
  def model_get_add_eos(_obj), do: :erlang.nif_error(:nif_not_loaded)
  def model_get_add_sep(_obj), do: :erlang.nif_error(:nif_not_loaded)
  def model_get_attr(_obj, _token), do: :erlang.nif_error(:nif_not_loaded)
  def model_get_score(_obj, _token), do: :erlang.nif_error(:nif_not_loaded)
  def model_get_text(_obj, _token), do: :erlang.nif_error(:nif_not_loaded)
  def model_is_control(_obj, _token), do: :erlang.nif_error(:nif_not_loaded)
  def model_is_eog(_obj, _token), do: :erlang.nif_error(:nif_not_loaded)
  def model_n_tokens(_obj), do: :erlang.nif_error(:nif_not_loaded)
  def model_vocab_type(_obj), do: :erlang.nif_error(:nif_not_loaded)
  def context_new(_model, _params), do: :erlang.nif_error(:nif_not_loaded)
  def context_sequence(_obj), do: :erlang.nif_error(:nif_not_loaded)
  def context_free_slots(_obj), do: :erlang.nif_error(:nif_not_loaded)
  def context_n_ctx(_obj), do: :erlang.nif_error(:nif_not_loaded)
  def context_can_shift(_obj), do: :erlang.nif_error(:nif_not_loaded)
  def context_perf(_obj), do: :erlang.nif_error(:nif_not_loaded)
  def sequence_logits(_obj), do: :erlang.nif_error(:nif_not_loaded)
  def sequence_is_empty(_obj), do: :erlang.nif_error(:nif_not_loaded)
  def sequence_push(_obj, _token), do: :erlang.nif_error(:nif_not_loaded)

  @doc """
  Re-decode the last token to refresh logits without pushing a new one.
  Useful after `pop()`, `remove()`, or other mutations that invalidate logits.
  """
  def sequence_decode(_obj), do: :erlang.nif_error(:nif_not_loaded)
  def sequence_pop(_obj), do: :erlang.nif_error(:nif_not_loaded)
  def sequence_len(_obj), do: :erlang.nif_error(:nif_not_loaded)
  def sequence_extend(_obj, _tokens), do: :erlang.nif_error(:nif_not_loaded)
  def sequence_get(_obj, _index), do: :erlang.nif_error(:nif_not_loaded)
  def sequence_remove(_obj, _range), do: :erlang.nif_error(:nif_not_loaded)
  def sequence_copy_to(_obj, _other, _range), do: :erlang.nif_error(:nif_not_loaded)
  def sequence_copy_from(_obj, _other, _range), do: :erlang.nif_error(:nif_not_loaded)
  def sequence_pos_min(_obj), do: :erlang.nif_error(:nif_not_loaded)
  def sequence_pos_max(_obj), do: :erlang.nif_error(:nif_not_loaded)
  def sequence_tokens(_obj), do: :erlang.nif_error(:nif_not_loaded)
  def sequence_kv_remove(_obj, _range), do: :erlang.nif_error(:nif_not_loaded)
  def sequence_kv_copy(_obj, _other, _range), do: :erlang.nif_error(:nif_not_loaded)
  def sequence_kv_shift(_obj, _range, _delta), do: :erlang.nif_error(:nif_not_loaded)
  def sequence_index(_obj, _index), do: :erlang.nif_error(:nif_not_loaded)
  def sequence_drop(_obj), do: :erlang.nif_error(:nif_not_loaded)
end
