# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a9e7e994415e90defeac2dfcf86da8be187ea3c0ba73d18b83281ad6c0968759
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule RustyLlama.Sequence do
  @moduledoc """
  A sequence handle. No lifetime parameters — holds a clone of the Context
  handle and communicates with the context actor via messages.

  Logits from the last `push()` are cached locally, so `sample()` and
  `logits()` don't need a second round-trip.
  """

  alias RustyLlama.Native

  defstruct [:ref]

  @typedoc "A sequence handle. No lifetime parameters — holds a clone of the Context handle and communicates with the context actor via messages."
  @type t :: %__MODULE__{ref: reference()}

  def logits(obj) do
    Native.sequence_logits(obj.ref)
  end

  def is_empty(obj) do
    Native.sequence_is_empty(obj.ref)
  end

  def push(obj, token) do
    Native.sequence_push(obj.ref, token)
  end

  @doc "Re-decode the last token to refresh logits without pushing a new one."
  def decode(obj) do
    Native.sequence_decode(obj.ref)
  end

  def pop(obj) do
    Native.sequence_pop(obj.ref)
  end

  def len(obj) do
    Native.sequence_len(obj.ref)
  end

  def extend(obj, tokens) do
    Native.sequence_extend(obj.ref, tokens)
  end

  def get(obj, index) do
    Native.sequence_get(obj.ref, index)
  end

  def remove(obj, range) do
    Native.sequence_remove(obj.ref, range)
  end

  def copy_to(obj, other, range) do
    Native.sequence_copy_to(obj.ref, other, range)
  end

  def copy_from(obj, other, range) do
    Native.sequence_copy_from(obj.ref, other, range)
  end

  def pos_min(obj) do
    Native.sequence_pos_min(obj.ref)
  end

  def pos_max(obj) do
    Native.sequence_pos_max(obj.ref)
  end

  def tokens(obj) do
    Native.sequence_tokens(obj.ref)
  end

  def kv_remove(obj, range) do
    Native.sequence_kv_remove(obj.ref, range)
  end

  def kv_copy(obj, other, range) do
    Native.sequence_kv_copy(obj.ref, other, range)
  end

  def kv_shift(obj, range, delta) do
    Native.sequence_kv_shift(obj.ref, range, delta)
  end

  def index(obj, index) do
    Native.sequence_index(obj.ref, index)
  end

  def drop(obj) do
    Native.sequence_drop(obj.ref)
  end
end
