// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a9e7e994415e90defeac2dfcf86da8be187ea3c0ba73d18b83281ad6c0968759
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef
/* eslint-disable */

export type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };

/**
 * Handle to a running context actor. Clone + Send + Sync.
 *
 * The actor thread is stopped when the last clone is dropped.
 */
export declare class Context {
  static new(model: Model, params: string): Context
  sequence(): Sequence | null
  freeSlots(): number
  nCtx(): number
  canShift(): boolean
  perf(): string
}

export declare enum DecodeError {
  SlotNotFound = "SlotNotFound",
  Aborted = "Aborted",
  InvalidInput = "InvalidInput",
  FatalError = "FatalError",
}

/**
 * Thread-safe handle to a loaded model.
 *
 * Cloning is cheap (Arc bump). Use from any thread.
 */
export declare class Model {
  static loadFromFile(path: string, params: string): Model
  asPtr(): string
  chatTemplate(name?: string | undefined | null): string | null
  desc(): string
  hasDecoder(): boolean
  decoderStartToken(): string | null
  hasEncoder(): boolean
  isDiffusion(): boolean
  isHybrid(): boolean
  isRecurrent(): boolean
  tokenToPiece(token: number): string
  tokenize(text: string, addSpecial: boolean, parseSpecial: boolean): Array<string>
  getAddBos(): boolean
  getAddEos(): boolean
  getAddSep(): boolean
  getAttr(token: string): string
  getScore(token: string): number
  getText(token: string): string
  isControl(token: string): boolean
  isEog(token: string): boolean
  nTokens(): number
  vocabType(): string
}

/**
 * A sequence handle. No lifetime parameters — holds a clone of the Context
 * handle and communicates with the context actor via messages.
 *
 * Logits from the last `push()` are cached locally, so `sample()` and
 * `logits()` don't need a second round-trip.
 */
export declare class Sequence {
  logits(): Array<number> | null
  isEmpty(): boolean
  push(token: string): void
  /**
   * Re-decode the last token to refresh logits without pushing a new one.
   * Useful after `pop()`, `remove()`, or other mutations that invalidate logits.
   */
  decode(): void
  pop(): string | null
  len(): number
  extend(tokens: Array<string>): void
  get(index: number): string | null
  remove(range: string): boolean
  copyTo(other: Sequence, range: string): void
  copyFrom(other: Sequence, range: string): void
  posMin(): string
  posMax(): string
  tokens(): Array<string>
  kvRemove(range: string): boolean
  kvCopy(other: Sequence, range: string): void
  kvShift(range: string, delta: string): void
  index(index: number): string
  drop(): void
}
