/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Handle to a running context actor. */
export declare class Context {
  static new(model: Model, nCtx: number, nBatch: number): Context
  sequence(): JsSequence | null
  freeSlots(): number
  nCtx(): number
  canShift(): boolean
}
export type JsContext = Context

/** Thread-safe handle to a loaded model. */
export declare class Model {
  static loadFromFile(path: string, nGpuLayers: number): Model
  chatTemplate(name?: string | undefined | null): string | null
  desc(): string
  hasDecoder(): boolean
  decoderStartToken(): number | null
  hasEncoder(): boolean
  isDiffusion(): boolean
  isHybrid(): boolean
  isRecurrent(): boolean
  tokenToPiece(token: number): string
  tokenize(text: string, addSpecial: boolean, parseSpecial: boolean): Array<number>
  getAddBos(): boolean
  getAddEos(): boolean
  getAddSep(): boolean
  getScore(token: number): number
  getText(token: number): string
  isControl(token: number): boolean
  isEog(token: number): boolean
  nTokens(): number
}
export type JsModel = Model

/** A sequence handle. */
export declare class Sequence {
  logits(): Array<number> | null
  isEmpty(): boolean
  push(token: number): void
  decode(): void
  pop(): number | null
  len(): number
  extend(tokens: Array<number>): void
  get(index: number): number | null
  posMin(): number
  posMax(): number
  tokens(): Array<number>
}
export type JsSequence = Sequence

export declare const enum DecodeError {
  SlotNotFound = 'SlotNotFound',
  Aborted = 'Aborted',
  InvalidInput = 'InvalidInput',
  FatalError = 'FatalError'
}
