// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:a9e7e994415e90defeac2dfcf86da8be187ea3c0ba73d18b83281ad6c0968759
// Re-generate with: alef generate
#![allow(dead_code, unused_imports, unused_variables)]
#![allow(unsafe_code)]
#![allow(clippy::too_many_arguments, clippy::let_unit_value, clippy::needless_borrow, clippy::map_identity, clippy::just_underscores_and_digits, clippy::unnecessary_cast, clippy::unused_unit, clippy::unwrap_or_default, clippy::derivable_impls, clippy::needless_borrows_for_generic_args, clippy::unnecessary_fallible_conversions, clippy::arc_with_non_send_sync, clippy::collapsible_if, clippy::clone_on_copy, clippy::should_implement_trait)]
#![allow(clippy::cast_possible_wrap, clippy::cast_possible_truncation, clippy::cast_sign_loss, clippy::default_trait_access, clippy::useless_conversion, clippy::unsafe_derive_deserialize, clippy::must_use_candidate, clippy::return_self_not_must_use, clippy::use_self, clippy::missing_const_for_fn, clippy::missing_errors_doc, clippy::needless_pass_by_value, clippy::doc_markdown, clippy::derive_partial_eq_without_eq, clippy::uninlined_format_args, clippy::redundant_clone, clippy::implicit_clone, clippy::redundant_closure_for_method_calls, clippy::wildcard_imports, clippy::option_if_let_else, clippy::too_many_lines)]

use napi::*;
use napi_derive::napi;
use rusty_llama::LlamaSampler;
use std::sync::Arc;
use std::sync::Mutex;


/// Wrapper for byte arrays that implements custom FromNapiValue to accept Buffer.from(...).
///
/// NAPI v3's default FromNapiValue for Vec<u8> expects Array[number], not Buffer.
/// This wrapper provides custom deserialization that accepts Buffer, Uint8Array, or Array,
/// converting them to Vec<u8>. Implements Clone and serde traits for use in struct fields.
#[derive(Clone, Debug, Default, serde::Serialize, serde::Deserialize)]
pub struct JsBytes(pub Vec<u8>);

impl From<Vec<u8>> for JsBytes {
    fn from(v: Vec<u8>) -> Self {
        JsBytes(v)
    }
}

impl From<JsBytes> for Vec<u8> {
    fn from(js_bytes: JsBytes) -> Self {
        js_bytes.0
    }
}

impl AsRef<[u8]> for JsBytes {
    fn as_ref(&self) -> &[u8] {
        &self.0
    }
}

impl std::ops::Deref for JsBytes {
    type Target = Vec<u8>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl std::ops::DerefMut for JsBytes {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}

impl napi::bindgen_prelude::FromNapiValue for JsBytes {
    unsafe fn from_napi_value(env: napi::sys::napi_env, napi_val: napi::sys::napi_value) -> napi::Result<Self> {
        use napi::bindgen_prelude::FromNapiValue;

        // Try Buffer first (most common for binary data in JS)
        if let Ok(buffer) = unsafe { napi::bindgen_prelude::Buffer::from_napi_value(env, napi_val) } {
            return Ok(JsBytes(buffer.as_ref().to_vec()));
        }

        // Try Uint8Array
        if let Ok(ua) = unsafe { napi::bindgen_prelude::Uint8Array::from_napi_value(env, napi_val) } {
            return Ok(JsBytes(ua.to_vec()));
        }

        // Fall back to Array[number]
        if let Ok(vec) = unsafe { Vec::<u8>::from_napi_value(env, napi_val) } {
            return Ok(JsBytes(vec));
        }

        Err(napi::Error::new(
            napi::Status::InvalidArg,
            "Expected Buffer, Uint8Array, or Array<number> for bytes field",
        ))
    }
}

impl napi::bindgen_prelude::ToNapiValue for JsBytes {
    unsafe fn to_napi_value(env: napi::sys::napi_env, val: Self) -> napi::Result<napi::sys::napi_value> {
        // Delegate to Vec<u8>'s implementation (which returns an Uint8Array/Buffer).
        unsafe { <Vec<u8> as napi::bindgen_prelude::ToNapiValue>::to_napi_value(env, val.0) }
    }
}


/// Thread-safe handle to a loaded model.
///
/// Cloning is cheap (Arc bump). Use from any thread.
#[derive(Clone)]#[napi(js_name = "Model")]pub struct JsModel {    inner: Arc<rusty_llama::Model>,}


#[napi]
impl JsModel {
    #[napi(js_name = "chatTemplate")]
    pub fn chat_template(&self, name: Option<String>) -> Option<String> {
        self.inner.chat_template(name.as_deref())
    }

    #[napi]
    pub fn desc(&self, ) -> String {
        self.inner.desc()
    }

    #[napi(js_name = "hasDecoder")]
    pub fn has_decoder(&self, ) -> bool {
        self.inner.has_decoder()
    }

    #[napi(js_name = "hasEncoder")]
    pub fn has_encoder(&self, ) -> bool {
        self.inner.has_encoder()
    }

    #[napi(js_name = "isDiffusion")]
    pub fn is_diffusion(&self, ) -> bool {
        self.inner.is_diffusion()
    }

    #[napi(js_name = "isHybrid")]
    pub fn is_hybrid(&self, ) -> bool {
        self.inner.is_hybrid()
    }

    #[napi(js_name = "isRecurrent")]
    pub fn is_recurrent(&self, ) -> bool {
        self.inner.is_recurrent()
    }

    #[allow(clippy::missing_errors_doc)]
    #[napi(js_name = "tokenToPiece")]
    pub fn token_to_piece(&self, token: i32) -> Result<String> {
        let result = self.inner.token_to_piece(token).map_err(|e| napi::Error::new(napi::Status::GenericFailure, e.to_string()))?;
        Ok(result)
    }

    #[napi(js_name = "getAddBos")]
    pub fn get_add_bos(&self, ) -> bool {
        self.inner.get_add_bos()
    }

    #[napi(js_name = "getAddEos")]
    pub fn get_add_eos(&self, ) -> bool {
        self.inner.get_add_eos()
    }

    #[napi(js_name = "getAddSep")]
    pub fn get_add_sep(&self, ) -> bool {
        self.inner.get_add_sep()
    }

    #[napi(js_name = "nTokens")]
    pub fn n_tokens(&self, ) -> i32 {
        self.inner.n_tokens()
    }
}

/// Handle to a running context actor. Clone + .
///
/// The actor thread is stopped when the last clone is dropped.
#[derive(Clone)]#[napi(js_name = "Context")]pub struct JsContext {    inner: Arc<rusty_llama::Context>,}


#[napi]
impl JsContext {
    #[napi]
    pub fn sequence(&self, ) -> Option<JsSequence> {
        self.inner.sequence().map(|v| JsSequence { inner: Arc::new(std::sync::Mutex::new(v)) })
    }

    #[napi(js_name = "freeSlots")]
    pub fn free_slots(&self, ) -> i64 {
        self.inner.free_slots() as i64
    }

    #[napi(js_name = "nCtx")]
    pub fn n_ctx(&self, ) -> u32 {
        self.inner.n_ctx()
    }

    #[napi(js_name = "canShift")]
    pub fn can_shift(&self, ) -> bool {
        self.inner.can_shift()
    }
}

/// A sequence handle. No lifetime parameters — holds a clone of the Context
/// handle and communicates with the context actor via messages.
///
/// Logits from the last `push()` are cached locally, so `sample()` and
/// `logits()` don't need a second round-trip.
#[derive(Clone)]#[napi(js_name = "Sequence")]pub struct JsSequence {    inner: Arc<std::sync::Mutex<rusty_llama::Sequence>>,}


#[napi]
impl JsSequence {
    #[napi]
    pub fn logits(&self, ) -> Option<Vec<f64>> {
        self.inner.lock().unwrap().logits()
    }

    #[napi(js_name = "isEmpty")]
    pub fn is_empty(&self, ) -> bool {
        self.inner.lock().unwrap().is_empty()
    }

    /// Re-decode the last token to refresh logits without pushing a new one.
    /// Useful after `pop()`, `remove()`, or other mutations that invalidate logits.
    #[napi]
    pub fn decode(&self, ) -> () {
        self.inner.lock().unwrap().decode()
    }

    #[napi]
    pub fn len(&self, ) -> i64 {
        self.inner.lock().unwrap().len() as i64
    }

    #[napi]
    pub fn drop(&self, ) -> () {
        self.inner.lock().unwrap().drop()
    }
}

#[napi(string_enum, js_name = "DecodeError")]
#[derive(Clone)]
pub enum JsDecodeError {
    SlotNotFound,
    Aborted,
    InvalidInput,
    FatalError,
}

#[allow(clippy::derivable_impls)]
impl Default for JsDecodeError {
    fn default() -> Self { Self::SlotNotFound }
}

impl From<rusty_llama::DecodeError> for JsDecodeError {
    fn from(val: rusty_llama::DecodeError) -> Self {
        match val {            rusty_llama::DecodeError::SlotNotFound => Self::SlotNotFound,            rusty_llama::DecodeError::Aborted => Self::Aborted,            rusty_llama::DecodeError::InvalidInput => Self::InvalidInput,            rusty_llama::DecodeError::FatalError => Self::FatalError,        }
    }
}
