// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:a9e7e994415e90defeac2dfcf86da8be187ea3c0ba73d18b83281ad6c0968759
// Re-generate with: alef generate
#![allow(dead_code, unused_imports, unused_variables)]
#![allow(clippy::too_many_arguments, clippy::let_unit_value, clippy::needless_borrow, clippy::map_identity, clippy::just_underscores_and_digits, clippy::unused_unit, clippy::unnecessary_cast, clippy::unwrap_or_default, clippy::derivable_impls, clippy::needless_borrows_for_generic_args, clippy::unnecessary_fallible_conversions)]

use rustler::ResourceArc;
use rustler::Encoder;
use rusty_llama::LlamaSampler;
use std::sync::Arc;

#[derive(Clone)]
pub struct Model {
    inner: Arc<rusty_llama::Model>,
}

// SAFETY: See gen_opaque_resource in alef-backend-rustler for rationale.

impl std::panic::RefUnwindSafe for Model {}

impl rustler::Resource for Model {}


#[derive(Clone)]
pub struct Context {
    inner: Arc<rusty_llama::Context>,
}

// SAFETY: See gen_opaque_resource in alef-backend-rustler for rationale.

impl std::panic::RefUnwindSafe for Context {}

impl rustler::Resource for Context {}


#[derive(Clone)]
pub struct Sequence {
    inner: Arc<rusty_llama::Sequence>,
}

// SAFETY: See gen_opaque_resource in alef-backend-rustler for rationale.

impl std::panic::RefUnwindSafe for Sequence {}

impl rustler::Resource for Sequence {}


#[derive(Debug, Clone, Copy, serde::Serialize, serde::Deserialize, rustler::NifUnitEnum)]
pub enum DecodeError {
    SlotNotFound,
    Aborted,
    InvalidInput,
    FatalError,
}

#[allow(clippy::derivable_impls)]
impl Default for DecodeError {
    fn default() -> Self {
        Self::SlotNotFound
 }
}


#[rustler::nif]
pub fn model_load_from_file(path: String, params: String) -> Result<ResourceArc<Model>, String> {
    Err(String::from("Not implemented: model_load_from_file"))
}


#[rustler::nif]
pub fn model_as_ptr(resource: rustler::ResourceArc<Model>) -> String {
    String::from("[unimplemented: model_as_ptr]")
}


#[rustler::nif]
pub fn model_chat_template(resource: rustler::ResourceArc<Model>, name: Option<String>) -> Option<String> {
    resource.inner.as_ref().chat_template(name.as_deref())
}


#[rustler::nif]
pub fn model_desc(resource: rustler::ResourceArc<Model>) -> String {
    resource.inner.as_ref().desc()
}


#[rustler::nif]
pub fn model_has_decoder(resource: rustler::ResourceArc<Model>) -> bool {
    resource.inner.as_ref().has_decoder()
}


#[rustler::nif]
pub fn model_decoder_start_token(resource: rustler::ResourceArc<Model>) -> Option<String> {
    None
}


#[rustler::nif]
pub fn model_has_encoder(resource: rustler::ResourceArc<Model>) -> bool {
    resource.inner.as_ref().has_encoder()
}


#[rustler::nif]
pub fn model_is_diffusion(resource: rustler::ResourceArc<Model>) -> bool {
    resource.inner.as_ref().is_diffusion()
}


#[rustler::nif]
pub fn model_is_hybrid(resource: rustler::ResourceArc<Model>) -> bool {
    resource.inner.as_ref().is_hybrid()
}


#[rustler::nif]
pub fn model_is_recurrent(resource: rustler::ResourceArc<Model>) -> bool {
    resource.inner.as_ref().is_recurrent()
}


#[rustler::nif]
pub fn model_token_to_piece(resource: rustler::ResourceArc<Model>, token: i32) -> Result<String, String> {
    let result = resource.inner.as_ref().token_to_piece(token).map_err(|e| e.to_string())?;
    Ok(result)

}


#[rustler::nif]
pub fn model_tokenize(resource: rustler::ResourceArc<Model>, text: String, add_special: bool, parse_special: bool) -> Vec<String> {
    Vec::new()
}


#[rustler::nif]
pub fn model_get_add_bos(resource: rustler::ResourceArc<Model>) -> bool {
    resource.inner.as_ref().get_add_bos()
}


#[rustler::nif]
pub fn model_get_add_eos(resource: rustler::ResourceArc<Model>) -> bool {
    resource.inner.as_ref().get_add_eos()
}


#[rustler::nif]
pub fn model_get_add_sep(resource: rustler::ResourceArc<Model>) -> bool {
    resource.inner.as_ref().get_add_sep()
}


#[rustler::nif]
pub fn model_get_attr(resource: rustler::ResourceArc<Model>, token: String) -> String {
    String::from("[unimplemented: model_get_attr]")
}


#[rustler::nif]
pub fn model_get_score(resource: rustler::ResourceArc<Model>, token: String) -> f32 {
    0.0
}


#[rustler::nif]
pub fn model_get_text(resource: rustler::ResourceArc<Model>, token: String) -> String {
    String::from("[unimplemented: model_get_text]")
}


#[rustler::nif]
pub fn model_is_control(resource: rustler::ResourceArc<Model>, token: String) -> bool {
    false
}


#[rustler::nif]
pub fn model_is_eog(resource: rustler::ResourceArc<Model>, token: String) -> bool {
    false
}


#[rustler::nif]
pub fn model_n_tokens(resource: rustler::ResourceArc<Model>) -> i32 {
    resource.inner.as_ref().n_tokens()
}


#[rustler::nif]
pub fn model_vocab_type(resource: rustler::ResourceArc<Model>) -> String {
    String::from("[unimplemented: model_vocab_type]")
}


#[rustler::nif]
pub fn context_new(model: rustler::ResourceArc<Model>, params: String) -> Result<ResourceArc<Context>, String> {
    Err(String::from("Not implemented: context_new"))
}


#[rustler::nif]
pub fn context_sequence(resource: rustler::ResourceArc<Context>) -> Option<ResourceArc<Sequence>> {
    resource.inner.as_ref().sequence().map(|v| ResourceArc::new(Sequence { inner: Arc::new(v) }))
}


#[rustler::nif]
pub fn context_free_slots(resource: rustler::ResourceArc<Context>) -> usize {
    resource.inner.as_ref().free_slots()
}


#[rustler::nif]
pub fn context_n_ctx(resource: rustler::ResourceArc<Context>) -> u32 {
    resource.inner.as_ref().n_ctx()
}


#[rustler::nif]
pub fn context_can_shift(resource: rustler::ResourceArc<Context>) -> bool {
    resource.inner.as_ref().can_shift()
}


#[rustler::nif]
pub fn context_perf(resource: rustler::ResourceArc<Context>) -> String {
    String::from("[unimplemented: context_perf]")
}


#[rustler::nif]
pub fn sequence_logits(resource: rustler::ResourceArc<Sequence>) -> Option<Vec<f32>> {
    resource.inner.as_ref().logits()
}


#[rustler::nif]
pub fn sequence_is_empty(resource: rustler::ResourceArc<Sequence>) -> bool {
    resource.inner.as_ref().is_empty()
}


#[rustler::nif]
pub fn sequence_push(resource: rustler::ResourceArc<Sequence>, token: String) -> () {
    ()
}


/// Re-decode the last token to refresh logits without pushing a new one.
/// Useful after `pop()`, `remove()`, or other mutations that invalidate logits.
#[rustler::nif]
pub fn sequence_decode(resource: rustler::ResourceArc<Sequence>) -> () {
    ()
}


#[rustler::nif]
pub fn sequence_pop(resource: rustler::ResourceArc<Sequence>) -> Option<String> {
    None
}


#[rustler::nif]
pub fn sequence_len(resource: rustler::ResourceArc<Sequence>) -> usize {
    resource.inner.as_ref().len()
}


#[rustler::nif]
pub fn sequence_extend(resource: rustler::ResourceArc<Sequence>, tokens: Vec<String>) -> () {
    ()
}


#[rustler::nif]
pub fn sequence_get(resource: rustler::ResourceArc<Sequence>, index: usize) -> Option<String> {
    None
}


#[rustler::nif]
pub fn sequence_remove(resource: rustler::ResourceArc<Sequence>, range: String) -> bool {
    false
}


#[rustler::nif]
pub fn sequence_copy_to(resource: rustler::ResourceArc<Sequence>, other: rustler::ResourceArc<Sequence>, range: String) -> () {
    ()
}


#[rustler::nif]
pub fn sequence_copy_from(resource: rustler::ResourceArc<Sequence>, other: rustler::ResourceArc<Sequence>, range: String) -> () {
    ()
}


#[rustler::nif]
pub fn sequence_pos_min(resource: rustler::ResourceArc<Sequence>) -> String {
    String::from("[unimplemented: sequence_pos_min]")
}


#[rustler::nif]
pub fn sequence_pos_max(resource: rustler::ResourceArc<Sequence>) -> String {
    String::from("[unimplemented: sequence_pos_max]")
}


#[rustler::nif]
pub fn sequence_tokens(resource: rustler::ResourceArc<Sequence>) -> Vec<String> {
    Vec::new()
}


#[rustler::nif]
pub fn sequence_kv_remove(resource: rustler::ResourceArc<Sequence>, range: String) -> bool {
    false
}


#[rustler::nif]
pub fn sequence_kv_copy(resource: rustler::ResourceArc<Sequence>, other: rustler::ResourceArc<Sequence>, range: String) -> () {
    ()
}


#[rustler::nif]
pub fn sequence_kv_shift(resource: rustler::ResourceArc<Sequence>, range: String, delta: String) -> () {
    ()
}


#[rustler::nif]
pub fn sequence_index(resource: rustler::ResourceArc<Sequence>, index: usize) -> String {
    String::from("[unimplemented: sequence_index]")
}


#[rustler::nif]
pub fn sequence_drop(resource: rustler::ResourceArc<Sequence>) -> () {
    ()
}


impl From<rusty_llama::DecodeError> for DecodeError {
    fn from(val: rusty_llama::DecodeError) -> Self {
        match val {            rusty_llama::DecodeError::SlotNotFound => Self::SlotNotFound,            rusty_llama::DecodeError::Aborted => Self::Aborted,            rusty_llama::DecodeError::InvalidInput => Self::InvalidInput,            rusty_llama::DecodeError::FatalError => Self::FatalError,        }
    }
}


fn on_load(env: rustler::Env, _info: rustler::Term) -> bool {
    env.register::<Model>().expect("Failed to register resource type Model");
    env.register::<Context>().expect("Failed to register resource type Context");
    env.register::<Sequence>().expect("Failed to register resource type Sequence");
    true
}

rustler::init!("Elixir.NativeModule.Native", load = on_load);
