# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a9e7e994415e90defeac2dfcf86da8be187ea3c0ba73d18b83281ad6c0968759
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule RustyLlama do
  @moduledoc "High-level API for rusty_llama"

  def model_load_from_file(path, params) do
    RustyLlama.Native.model_load_from_file(path, params)
  end

  def model_as_ptr(obj) do
    RustyLlama.Native.model_as_ptr(obj)
  end

  def model_chat_template(obj, name) do
    RustyLlama.Native.model_chat_template(obj, name)
  end

  def model_desc(obj) do
    RustyLlama.Native.model_desc(obj)
  end

  def model_has_decoder(obj) do
    RustyLlama.Native.model_has_decoder(obj)
  end

  def model_decoder_start_token(obj) do
    RustyLlama.Native.model_decoder_start_token(obj)
  end

  def model_has_encoder(obj) do
    RustyLlama.Native.model_has_encoder(obj)
  end

  def model_is_diffusion(obj) do
    RustyLlama.Native.model_is_diffusion(obj)
  end

  def model_is_hybrid(obj) do
    RustyLlama.Native.model_is_hybrid(obj)
  end

  def model_is_recurrent(obj) do
    RustyLlama.Native.model_is_recurrent(obj)
  end

  def model_token_to_piece(obj, token) do
    RustyLlama.Native.model_token_to_piece(obj, token)
  end

  def model_tokenize(obj, text, add_special, parse_special) do
    RustyLlama.Native.model_tokenize(obj, text, add_special, parse_special)
  end

  def model_get_add_bos(obj) do
    RustyLlama.Native.model_get_add_bos(obj)
  end

  def model_get_add_eos(obj) do
    RustyLlama.Native.model_get_add_eos(obj)
  end

  def model_get_add_sep(obj) do
    RustyLlama.Native.model_get_add_sep(obj)
  end

  def model_get_attr(obj, token) do
    RustyLlama.Native.model_get_attr(obj, token)
  end

  def model_get_score(obj, token) do
    RustyLlama.Native.model_get_score(obj, token)
  end

  def model_get_text(obj, token) do
    RustyLlama.Native.model_get_text(obj, token)
  end

  def model_is_control(obj, token) do
    RustyLlama.Native.model_is_control(obj, token)
  end

  def model_is_eog(obj, token) do
    RustyLlama.Native.model_is_eog(obj, token)
  end

  def model_n_tokens(obj) do
    RustyLlama.Native.model_n_tokens(obj)
  end

  def model_vocab_type(obj) do
    RustyLlama.Native.model_vocab_type(obj)
  end

  def context_new(model, params) do
    RustyLlama.Native.context_new(model, params)
  end

  def context_sequence(obj) do
    RustyLlama.Native.context_sequence(obj)
  end

  def context_free_slots(obj) do
    RustyLlama.Native.context_free_slots(obj)
  end

  def context_n_ctx(obj) do
    RustyLlama.Native.context_n_ctx(obj)
  end

  def context_can_shift(obj) do
    RustyLlama.Native.context_can_shift(obj)
  end

  def context_perf(obj) do
    RustyLlama.Native.context_perf(obj)
  end

  def sequence_logits(obj) do
    RustyLlama.Native.sequence_logits(obj)
  end

  def sequence_is_empty(obj) do
    RustyLlama.Native.sequence_is_empty(obj)
  end

  def sequence_push(obj, token) do
    RustyLlama.Native.sequence_push(obj, token)
  end

  @doc "Re-decode the last token to refresh logits without pushing a new one."
  def sequence_decode(obj) do
    RustyLlama.Native.sequence_decode(obj)
  end

  def sequence_pop(obj) do
    RustyLlama.Native.sequence_pop(obj)
  end

  def sequence_len(obj) do
    RustyLlama.Native.sequence_len(obj)
  end

  def sequence_extend(obj, tokens) do
    RustyLlama.Native.sequence_extend(obj, tokens)
  end

  def sequence_get(obj, index) do
    RustyLlama.Native.sequence_get(obj, index)
  end

  def sequence_remove(obj, range) do
    RustyLlama.Native.sequence_remove(obj, range)
  end

  def sequence_copy_to(obj, other, range) do
    RustyLlama.Native.sequence_copy_to(obj, other, range)
  end

  def sequence_copy_from(obj, other, range) do
    RustyLlama.Native.sequence_copy_from(obj, other, range)
  end

  def sequence_pos_min(obj) do
    RustyLlama.Native.sequence_pos_min(obj)
  end

  def sequence_pos_max(obj) do
    RustyLlama.Native.sequence_pos_max(obj)
  end

  def sequence_tokens(obj) do
    RustyLlama.Native.sequence_tokens(obj)
  end

  def sequence_kv_remove(obj, range) do
    RustyLlama.Native.sequence_kv_remove(obj, range)
  end

  def sequence_kv_copy(obj, other, range) do
    RustyLlama.Native.sequence_kv_copy(obj, other, range)
  end

  def sequence_kv_shift(obj, range, delta) do
    RustyLlama.Native.sequence_kv_shift(obj, range, delta)
  end

  def sequence_index(obj, index) do
    RustyLlama.Native.sequence_index(obj, index)
  end

  def sequence_drop(obj) do
    RustyLlama.Native.sequence_drop(obj)
  end
end
