//! Raw FFI bindings to llama.cpp generated by bindgen.
//!
//! This crate provides unsafe FFI bindings to the llama.cpp C API.
//! For a safe high-level interface, see the `handholding` crate.
//!
//! # Safety
//!
//! All functions in this crate are unsafe and require careful handling of raw pointers.
//! Refer to the llama.cpp documentation for proper usage.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(rustdoc::bare_urls)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
